---
- name : Play to patch VM in inventory
  hosts: all
  serial: "{{serial}}"
  roles:
    - name: Display Current VM Info
      role: display vm info
    - name: patch the vm
      role: patch vm
	
- name: play to see updates
  hosts: all
  roles:
     -name: display update info
      role: vm info
